baseURL      = "https://magiconair.net/"
languageCode = "en-us"
title        = "magiconair - Frank Schröder"

[params]
  fabioURL        = "https://fabio.netlify.com/"
  googleAnalytics = "UA-2812942-2"
